apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: rollout-reporter-sa
  namespace: codefresh

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rollout-reporter-sa
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: rollout-reporter-sa
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: rollout-reporter-sa
subjects:
- kind: ServiceAccount
  name: rollout-reporter-sa
  namespace: codefresh
